app/main/forms.py
# -*- coding: utf-8 -*-
from flask_wtf import FlaskForm
from app.models import get_doctors, get_diagnosis
from wtforms.fields import StringField, SelectField, FormField, SubmitField, TextAreaField
from wtforms.fields.html5 import DateField
from wtforms.ext.sqlalchemy.fields import QuerySelectField, QuerySelectMultipleField
from wtforms.validators import InputRequired, Optional, Email, Regexp

class PatientForm(FlaskForm):
    doctor = QuerySelectField('Doctors',
                              query_factory=get_doctors,
                              get_label='formatted_name',
                              allow_blank=True)
    
    diagnosis = QuerySelectMultipleField('Diagnoses',
                                         query_factory=get_diagnosis,
                                         get_label='name',
                                         allow_blank=True)

class PatientPhiForm(PatientForm):
    fname = StringField('First name',
                        validators = [InputRequired()])
    lname = StringField('Last name',
                        validators = [InputRequired()])
    gender = SelectField('Gender',
                         choices = [('male', 'male'),
                                    ('female','female')])
    dob = DateField('Date of birth', format='%Y-%m-%d',
                    validators = [InputRequired()])
    submit = SubmitField('Add Patient')
    

class DoctorForm(FlaskForm):
    fname = StringField('First name',
                        validators = [InputRequired()])
    lname = StringField('Last name',
                        validators = [InputRequired()])
    phone = StringField('Phone #',
                        validators = [Optional(), Regexp("\d{3}[ ,-]?\d{3}[ ,-]?\d{4}", message="Phone number format NNN-NNN-NNNN")])
    fax = StringField('Fax #',
                      validators = [Optional(), Regexp("\d{3}[ ,-]?\d{3}[ ,-]?\d{4}", message="Phone number format NNN-NNN-NNNN")])
    email = StringField('Email',
                        validators=[Optional(), Email()])
    prefered_contact = SelectField('Prefered contact method',
                                   choices = [('fax','fax'),
                                              ('email', 'email'),
                                              ('both', 'both')],
                                   validators = [InputRequired()])
    
    submit = SubmitField('Add Doctor')
    
class DiagnosisForm(FlaskForm):
    name = StringField('Name',
                       validators = [InputRequired()])
    submit = SubmitField('Add Diagnosis')
    
class VisitForm(FlaskForm):
    dov = DateField('Date of visit', format='%Y-%m-%d',
                    validators = [InputRequired()])
    notes = TextAreaField(label=u'Notes',
                          description='Visit notes (not included on report)',
                          validators=[Optional()])

app/main/__init__.py
# -*- coding: utf-8 -*-

from flask import Blueprint

bp = Blueprint('main', __name__,
               template_folder='templates')

from app.main import routes

app/main/routes.py
# -*- coding: utf-8 -*-
from flask import render_template, flash, session, redirect, url_for

from app import db
from app.main import bp
from app.main.forms import PatientForm, PatientPhiForm, DoctorForm, DiagnosisForm, VisitForm
from app.main.utils import collapse_phone, format_phone
from app.models import Patient, PatientPHI, Doctor, Diagnosis, Visit

@bp.route('/', methods=['GET', 'POST'])
@bp.route('/index', methods=['GET', 'POST'])
def index():
    if session.get('key'):
        flash('Session value set: {}'.format(session.get('key')))
        session.pop('key')
    return render_template('index.html', title="Home")

@bp.route('/add_patient', methods=['GET', 'POST'])
def add_patient(form_ptn=None):
    """
    Accepts form_ptn as an optional variable so can pass back 
    already entered patient information if modals are used to
    add doctors or diagnosis.
    """
    if not form_ptn:
        form_ptn = PatientPhiForm()
    form_doctor = DoctorForm()
    form_diagnosis = DiagnosisForm()
    
    if form_ptn.validate_on_submit():
        ptn_phi = PatientPHI.query.filter_by(lname=form_ptn.lname.data,
                                          fname=form_ptn.fname.data,
                                          dob=form_ptn.dob.data).first()
        if ptn_phi:
            flash('Patient already exists')
            return redirect(url_for('main.patient', id=ptn_phi.patient.id))
        else:
            ptn_phi = PatientPHI(lname=form_ptn.lname.data,
                                 fname=form_ptn.fname.data,
                                 dob=form_ptn.dob.data,
                                 gender=form_ptn.gender.data)
            ptn_phi.patient = Patient()
            ptn_phi.patient.doctor = form_ptn.doctor.data
            ptn_phi.patient.diagnoses = form_ptn.diagnosis.data
            db.session.add(ptn_phi)
            db.session.commit()
            return redirect(url_for('main.patient', id=ptn_phi.patient.id))

    return render_template('edit_patient.html',
                           form=form_ptn,
                           form_adddoctor=form_doctor,
                           form_adddiagnosis=form_diagnosis)
    
@bp.route('/add_doctor', methods=['POST'])
def add_doctor():
    form = DoctorForm()
    form_ptn = PatientPhiForm()
    if form.validate_on_submit():
        phone = collapse_phone(form.phone.data)
        fax = collapse_phone(form.fax.data)
        doctor = Doctor(fname=form.fname.data,
                        lname=form.lname.data,
                        phone=phone,
                        fax=fax,
                        email=form.email.data)
        db.session.add(doctor)
        db.session.commit()
        flash('Added doctor')
    else:
        flash('Failed adding doctor')
    return redirect(url_for('main.add_patient', ptn_form=form_ptn))


@bp.route('/add_diagnosis', methods=['POST'])
def add_diagnosis():
    form = DiagnosisForm()
    form_ptn = PatientPhiForm()
    if form.validate_on_submit():
        diagnosis = Diagnosis(name=form.name.data)
        db.session.add(diagnosis)
        db.session.commit()
        flash('Added diagnosis')
    else:
        flash('Failed adding diagnosis')
    return redirect(url_for('main.add_patient', ptn_form=form_ptn))

@bp.route('/list_patients', methods=['GET'])
def list_patients():
    qry = Patient.\
        query.\
        join(PatientPHI).\
        order_by(PatientPHI.lname)
    patients = qry.all()
    return render_template('patient_list.html', patients=patients)

@bp.route('/patient/<id>')
def patient(id):
    patient = Patient.query.filter_by(id=id).first_or_404()
    return render_template('patient.html', p=patient)

@bp.route('/add_visit/<patient_id>', methods=['Get','POST'])
def add_visit(patient_id):
    patient = Patient.query.filter_by(id=patient_id).first()
    if not patient:
        flash("Invalid patient")
        return redirect(url_for('main.list_patients'))
    form = VisitForm()
    if form.validate_on_submit():
        visit = Visit.query.filter_by(patient_id=patient.id,
                                      visit_date=form.dov.data).first()
        if not visit:
            visit=Visit(patient_id=patient.id,
                        visit_date=form.dov.data)
        visit.notes=form.notes.data
        db.session.add(visit)
        db.session.commit()
        return redirect(url_for('main.patient', id=patient.id))

app/main/templates/_add_diagnosis_modal.html
<!-- Modal -->
<div class="modal fade" id="modal_add_diagnosis" tabindex="-1" role="dialog" aria-labelledby="modal_add_diagnosis_label">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="modal_add_diagnosis_label">Add Diagnosis</h4>
            </div>
            <div class="modal-body">
                <form method="post" action={{url_for('main.add_diagnosis') }} name="add_diagnosis", class="form-horizontal", role="form">
                    {{ form_adddiagnosis.hidden_tag() }}
                    <div class="form-group">
                        {{ form_adddiagnosis.name.label() }}
                        {{ form_adddiagnosis.name() }}
                    </div>
                    {{ form_adddiagnosis.submit() }}
                </form>
            </div>
        </div>
    </div>
</div>

app/main/templates/_add_doctor_modal.html
<!-- Modal -->
<div class="modal fade" id="modal_add_doctor" tabindex="-1" role="dialog" aria-labelledby="modal_add_doctor_label">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="modal_add_doctor_label">Add doctor</h4>
            </div>
            <div class="modal-body">
                <form method="post" action={{url_for('main.add_doctor') }} name="add_doctor", class="form-horizontal", role="form">
                    {{ form_adddoctor.hidden_tag() }}
                    <div class="form-group">
                        {{ form_adddoctor.fname.label() }}
                        {{ form_adddoctor.fname() }}
                    </div>
                    <div class="form-group">
                        {{ form_adddoctor.lname.label() }}
                        {{ form_adddoctor.lname() }}
                    </div>
                    <div class="form-group">
                        {{ form_adddoctor.phone.label() }}
                        {{ form_adddoctor.phone() }}
                    </div>
                    <div class="form-group">
                        {{ form_adddoctor.fax.label() }}
                        {{ form_adddoctor.fax() }}
                    </div>
                    <div class="form-group">
                        {{ form_adddoctor.email.label() }}
                        {{ form_adddoctor.email() }}
                    </div>
                    <div class="form-group">
                        {{ form_adddoctor.prefered_contact.label() }}
                        {{ form_adddoctor.prefered_contact() }}
                    </div>
                    {{ form_adddoctor.submit() }}
                </form>
            </div>
        </div>
    </div>
</div>

app/main/templates/_patient.html
<div class="panel panel-default" data-href="{{ url_for('main.patient', id=p.id) }}">
    <div class="panel-heading">
        <h4 class="panel-title">Family name: {{ p.phi.lname }}</h4>
    </div>
    <ul>
        <li>First Name:{{ p.phi.fname }}</li>
        <li>DoB: {{ p.phi.dob }}</li>
        <li>Gender: {{ p.phi.gender }}</li>
    </ul>
</div>

app/main/templates/_visit.html
<div class="panel panel-default"  data-href="{{ url_for('reports.report', visit_id=visit.id) }}">
    <div class="panel-header">
        <h4>Date: {{ visit.visit_date }}</h4>
    </div>
    <div class="panel-content">
        {% if visit.report %}
            <span>Tests Performed:</span>
            {% if visit.report.erg_complete %}
                <span>ERG</span>
            {% endif %}
            {% if visit.report.mferg_complete %}
                <span>mfERG</span>
            {% endif %}
            {% if visit.report.vep_complete %}
                <span>VEP</span>
            {% endif %}
            {% if visit.report.eog_complete %}
                <span>EOG</span>
            {% endif %}
            <p> {{ visit.report.overview_comment }}</p>
        {% endif %}
    </div>
</div>
        

app/main/templates/edit_patient.html
{% extends "base.html" %}
{% block modals %}
    {% include '_add_doctor_modal.html' %}
    {% include '_add_diagnosis_modal.html' %}
{% endblock %}
{% block app_content %}
    <h1>Patient</h1>
    <div class="container">
        <form class="form-horizontal", method="POST", role="form">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.fname.label() }}
            {{ form.fname(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.lname.label() }}
            {{ form.lname(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.gender.label() }}
            {{ form.gender(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.dob.label() }}
            {{ form.dob(class="form-control") }}
        </div>
        <div class="input-group">
            <div class="form-group">
                {{ form.doctor.label() }}
                {{ form.doctor(class="form-control") }}
                <button class="btn btn-primary" data-toggle="modal" data-target="#modal_add_doctor" type="button">
                    Add new doctor
                </button>
            </div>
        </div>
        <div class="input-group">
            <div class="form-group">
                {{ form.diagnosis.label() }}
                {{ form.diagnosis(class="form-control") }}
                <button class="btn btn-primary" data-toggle="modal" data-target="#modal_add_diagnosis" type="button">
                    Add new diagnosis
                </button>
            </div>
        </div>
        {{ form.submit() }}
        </form>
    </div>

{% endblock %}

app/main/templates/edit_visit.html
{% extends "base.html" %}

{% block app_content %}
<h1>Visit</h1>
    <div class="container">
        <form class="form-horizontal", method="POST", role="form">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.dob.label() }}
            {{ form.dob(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.notes.label() }}
            {{ form.notes(class="form=control") }}
        </div>
    </div>
{% endblock %}

app/main/templates/patient.html
{% extends 'base.html' %}
{% block app_content %}
<div class="panel panel-default"
    <div class="panel-heading">
        Name: {{ p.phi.fname }} {{ p.phi.lname }}
        DoB: {{ p.phi.dob }}
        <span class="pull-right"><span class="glyphicon glyphicon-plus" aria-hidden="true"</span> Add visit</span>
    </div>
    <table class="table table-striped">
        {% for visit in p.visits %}
            <tr>
                {% include '_visit.html' %}
            </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

app/main/templates/patient_list.html
{% extends "base.html" %}
{% block app_content %}
<div class="row">
    {% for p in patients %}
        <div class="col-xs-4 col-sm-3 col-md-3">
            {% include '_patient.html' %}
        </div>
    {% endfor %}
</div>
{% endblock %}
