app/imports/forms.py
# -*- coding: utf-8 -*-

from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired
from wtforms import SubmitField

class DataForm(FlaskForm):
    data_file = FileField(validators=[FileRequired()])
    submit = SubmitField('Upload')

app/imports/__init__.py
# -*- coding: utf-8 -*-

from flask import Blueprint

bp = Blueprint('imports', __name__,
               template_folder='templates')

from app.imports import routes

app/imports/routes.py
# -*- coding: utf-8 -*-
import os
from tempfile import mkdtemp
from werkzeug.utils import secure_filename

from flask import render_template, redirect, flash, session

from app.imports import bp
from app.imports.store import load_data

from app.imports.forms import DataForm

@bp.route('/import', methods=['GET', 'POST'])
def upload_data():
    """
    Upload a patient datafile,
    Creates a server side copy of the data
    """
    form = DataForm()
    
    if form.validate_on_submit():
        data = form.data_file.data
        filename = secure_filename(data.filename)
        flash('File:{} uploaded'.format(filename))
        tempdir = mkdtemp(prefix='patientDb_')
        target_file = os.path.join(tempdir, filename)
        data.save(target_file)
        session['upload_file'] = target_file
        load_data(target_file)
        
    return render_template('import.html', title='Import', form=form)

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/site.css') }}">
{% endblock %}

{% block title %}
    {% if title %}
        {{ title }} - Patient Database
    {% else %}
        Patient Database
    {% endif %}
{% endblock %}


{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">PatientDb</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.index') }}">Home</a></li>
                    <li><a href="{{ url_for('imports.upload_data') }}">Upload</a></li>
                    <li><a href="{{ url_for('main.list_patients') }}">Patients</a></li>
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    {% block modals %}{% endblock %}
    <div class='container'>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert.info" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}
        
        {% block app_content %}{% endblock %}
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
    <!-- <script src="static/js/plotly-latest.min.js"></script> -->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script type="text/javascript" src="/static/js/site.js"></script>
    <script type="text/javascript">
    $(document).on('click', '.panel[data-href]:not(a)', function(){
        window.location = $(this).attr('data-href');
    });
    </script>
{% endblock %}

app/templates/import.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Import Data</h1>
    <div class="row">
        <div class-"col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1>Patient DB</h1>
<p>Be patient this is a work in progress</p>
{% endblock %}

app/templates/ptn_button.snip.html
<div class="card">
    <div class="card-body">
    <h5 class="card-title">Family Name: </b>{{ ptn.phi.lname }}</h5>
    <ul class="list-group">
    <li class="list-group-item">First Name: {{ ptn.phi.fname }}</li>
    <li class="list-group-item">DOB: {{ ptn.phi.dob.strftime("%Y-%m-%d") }}</li>
    <li class="list-group-item">Gender: {{ ptn.phi.gender }}</li>
    <li class="list-group-item">Record #: {{ ptn.id }}</li>
    </ul>
 </div>

app/templates/store_data.html
{% extends "base.html" %}

{% block content %}
    <div>
        <h1>Store Data</h1>
        {% if ptn %}
            <h2>Found a patient:</h2>
            {% include 'ptn_button.snip.html' %}
        {% else %}
            <h2>Patient not found</h2>
        {% endif %}
    </div>
    <div>
        <a href="{{url_for('store_data', confirm=True) }}" class="btn btn-success">Confirm</a>
        <a href="{{url_for('store_data', confirm=False) }}" class="btn btn-warning">Cancel</a>
    </div>
{% endblock %}